name: Bug Report
description: File a bug report - make sure it's reproducible and not just your machine.
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a bug report!
        * Be sure to answer **all** of the questions below.
        * Provide lots of detail. Too much info is better than not enough.
        * If we can't reproduce the issue, we can't fix it.
  - type: textarea
    attributes:
      label: What were you trying to do?
      description: Clearly describe what you were trying to do when you found this bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why were you trying to do this?
      description: Explain why you were trying to do this.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How did you attempt to do it?
      description: Clearly describe, in detail, how you attempted to do this. Include both prose and code snippets in your response.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What actually happened?
      description: Clearly describe what actually happened as a result of what you attempted. Be sure to include all relevant stacktraces, CLI output, and screenshots.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to happen?
      description: Clearly describe what you expected to happen as a result of what you attempted. Include examples of what you expected in your response.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How can we reproduce the issue?
      description: |
        Type out a list of specific steps we can take to reproduce the bug you've found. Your response must include both prose and code snippets. You must attach (or provides links to) any PDFs, images, or other files necessary to complete the steps.
        > If you are unable to share certain files (e.g. confidential PDFs), then state this in your response.
        > Be prepared to share the files privately (e.g. via email).
        > If you are unable to do this then we probably can't fix the issue.

        Your response should include **complete**, **executable** code, ideally in the form of a git repo.

        If your response only includes incomplete code or doesn't clearly state how to execute the code you've provided, your report will be closed without comment.
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: What version of `pdf-lib` are you using?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What environment are you running pdf-lib in?
      multiple: true
      options:
        - Browser
        - Node
        - Deno
        - React Native
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Notes
      description: |
        Please provide any additional information or observations here.
      placeholder: Tell us what you see!
    validations:
      required: false
